version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: extrahoursdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    networks:
      - extrahours-net

  backend:
    build:
      context: ./ExtraHours.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=extrahoursdb;user=user;password=user123;
      - Jwt__Key=12345678901234567890123456789012
      - Jwt__Issuer=http://backend:5023
      - Jwt__Audience=http://frontend:80
    networks:
      - extrahours-net
    depends_on:
      - mysql
    ports:
      - "5023:5023"
    # Opcional: eliminar wait-for-it si da problemas
    # command: ./wait-for-it.sh mysql:3306 --timeout=30 --strict -- dotnet ExtraHours.API.dll

  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://backend:5023/api
    networks:
      - extrahours-net
    depends_on:
      - backend
    ports:
      - "5173:80"

networks:
  extrahours-net:
